---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/rukbanor/public_html/fishgelatine.co.za/v2/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -a --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
